### ISSUE TITLE
Shebang independent of system configuration

### ISSUE THREAD

**Issue by Neato-Nick** [knausb/fasta2nuccomp#5]
When executed on command line, the script fails if invoked by itself rather than through python3

```
$ fasta2nuccomp.py
bash: ./fasta2nuccomp.py: /usr/bin/python3: bad interpreter: No such file or directory
$ python3 fasta2nuccomp.py
usage: fasta2nuccomp.py [-h] [-v] FASTA
fasta2nuccomp.py: error: the following arguments are required: FASTA
```

Pretty sure it's just a simple issue related to the shebang line in fasta2nuccomp.py: `#!/usr/bin/python3`
The interpreter relies on finding `python3` in `/usr/bin`. The safer way to do this is a shebang like
`#!/usr/bin/env python3`

Which looks for python3 in the environment its executed in, i.e. the $PATH, rather than in a particular location.
Only hesitant to do a pull request because I'm not 100% positive this is the correct fix, but it's one[ I've seen before](https://github.com/davidemms/OrthoFinder/blob/master/orthofinder.py). Might want to check some more well-produced python libraries.

**Comment by knausb** [comment]
Naw, I think you're correct. I think I'm writing python like I used to write perl. But you've reminded me that the python folks are trying to be a bit more platform independent. Thanks, and thanks for catching the typo too!
